services:
  drone-server:
    image: drone/drone:2
    ports:
      - 192.168.20.6:80:80
      - 192.168.20.6:443:443
    networks:
      macvlan:
        ipv4_address: 192.168.20.6
        ipv6_address: 2601:c6:8300:1df::84
      default:
    volumes:
      - drone_data:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - "${ENV_DIR:-}/compose/drone-stack/drone.env"
      - "${ENV_DIR:-}/compose/drone-stack/postgres.env"
    restart: always
    environment:
      - DRONE_GITHUB_SKIP_VERIFY=true
      - DRONE_AGENTS_ENABLED=true
      - DRONE_SERVER_HOST=drone-cynicsoft.duckdns.org
      - DRONE_SERVER_PROTO=https
      - DRONE_TLS_AUTOCERT=false
      - DRONE_OPEN=false
      - DRONE_GITHUB=true
      # - DRONE_LOGS_TRACE=true 
    labels:
      - homepage.name=Drone CI
      - homepage.group=Network
      - homepage.icon=https://github.com/modem7/MiscAssets/blob/master/Icons/Dashboard-Icons/droneblue.png
      - homepage.href=https://drone.cynicsoft.net/
      - homepage.description=Continuous Integration platform

  # https://github.com/meltwater/drone-convert-pathschanged
  drone-convert-pathschanged:
    image: meltwater/drone-convert-pathschanged
    networks:
      - default
    env_file: ["${ENV_DIR:-}/compose/drone-stack/drone-convert-pathschanged.env"]
    expose: 
      - 3000
    restart: always
    # environment:
    #   - DRONE_DEBUG=true

  postgres:
    image: postgres:10
    hostname: drone-postgres 
    env_file: ["${ENV_DIR:-}/compose/drone-stack/postgres.env"]
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  drone_data:
    driver_opts:
      type: nfs
      o: addr=${NAS_HOST},nolock,noresvport,vers=2
      device: :${DATADIR}/drone-stack/data
  postgres_data:
    driver_opts:
      type: nfs
      o: addr=${NAS_HOST},nolock,noresvport,vers=2
      device: :${DATADIR}/drone-stack/postgres


networks:
  default:
    name: drone-stack_default
    driver: overlay
    attachable: true
  macvlan:
    external: true
    name: docker-macvlan