version: '3.5'

services:
  drone-server:
    image: drone/drone:2
    ports:
      - 192.168.20.6:80:80
      - 192.168.20.6:443:443
    networks:
      macvlan:
        ipv4_address: 192.168.20.6
        ipv6_address: 2601:c6:8300:1df::84
      drone:
    volumes:
      - drone_data:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: [drone-stack_drone.env]
    restart: always
    environment:
      - DRONE_GITHUB_SKIP_VERIFY=true
      - DRONE_AGENTS_ENABLED=true
      - DRONE_SERVER_HOST=drone-cynicsoft.duckdns.org
      - DRONE_SERVER_PROTO=https
      - DRONE_TLS_AUTOCERT=false
      - DRONE_OPEN=false
      - DRONE_GITHUB=true
      # - DRONE_LOGS_TRACE=true 
      # Variables below set via drone.env file
      # - DRONE_USER_CREATE=
      # - DRONE_USER_FILTER=
      # - DRONE_GITHUB_CLIENT_ID=
      # - DRONE_GITHUB_CLIENT_SECRET=
      # - DRONE_RPC_SECRET=

  drone-agent:
    image: drone/agent:1
    command: agent
    restart: always
    depends_on:
      - drone-server
    networks:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: [drone-stack_drone.env]
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone-server
      # - DRONE_LOGS_TRACE=true 
      # Variables below set via drone.env file
      # - DRONE_RPC_SECRET=


volumes:
  drone_data:
    driver_opts:
      type: nfs
      o: addr=avengershq.cynicsoft.net,nolock,noresvport,vers=2
      device: :${DATADIR}/drone-stack/data


networks:
  drone:
    name: drone_network
  macvlan:
    external: true
    name: docker-macvlan